version: "3"

services:
  server:
    container_name: athletes-server
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - yarn_cache:/usr/local/share/.cache/yarn/
    depends_on:
      - db
  client:
    container_name: athletes-client
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - yarn_cache:/usr/local/share/.cache/yarn/
    depends_on:
      - db
  db:
    container_name: athletes-db
    image: mariadb:10.5.6
    environment:
      - MYSQL_ROOT_HOST=% 
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - ./server/db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
volumes:
  yarn_cache: