POST http://localhost:3001/api/athlete/
content-type: application/json

{
    "firstNames": "Testi REST",
    "nickName": "Testi",
    "lastName": "Henkilö",
    "weight": "",
    "achievements": []
}